version: '3.8'

services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=5

  app:
    build: .
    depends_on:
      - selenium-chrome
    environment:
      - SELENIUM_REMOTE_URL=http://selenium-chrome:4444/wd/hub
    links:
      - selenium-chrome
    command: ["java", "-jar", "target/bitcoin-news-scraper-1.0-SNAPSHOT.jar"]